// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmY7wJKt6vRj-9Y2v_2MtZY399R2LN81Y',
    appId: '1:974146683624:web:0f7ae8c5d5ea3a74ab3f5d',
    messagingSenderId: '974146683624',
    projectId: 'raices-vivas-7ad92',
    authDomain: 'raices-vivas-7ad92.firebaseapp.com',
    storageBucket: 'raices-vivas-7ad92.firebasestorage.app',
    measurementId: 'G-T2G4GCSEK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyA-bEJjjaREQI8v3NuYSPQtmYrE7uFcQ',
    appId: '1:974146683624:android:8d2deb051f66f601ab3f5d',
    messagingSenderId: '974146683624',
    projectId: 'raices-vivas-7ad92',
    storageBucket: 'raices-vivas-7ad92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNRTPLS_30QMesDnPy6lp7PqdGCg4fNEs',
    appId: '1:974146683624:ios:110be4f9add59ddaab3f5d',
    messagingSenderId: '974146683624',
    projectId: 'raices-vivas-7ad92',
    storageBucket: 'raices-vivas-7ad92.firebasestorage.app',
    iosBundleId: 'com.example.raicesVivas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNRTPLS_30QMesDnPy6lp7PqdGCg4fNEs',
    appId: '1:974146683624:ios:110be4f9add59ddaab3f5d',
    messagingSenderId: '974146683624',
    projectId: 'raices-vivas-7ad92',
    storageBucket: 'raices-vivas-7ad92.firebasestorage.app',
    iosBundleId: 'com.example.raicesVivas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmY7wJKt6vRj-9Y2v_2MtZY399R2LN81Y',
    appId: '1:974146683624:web:1d870efa92f20795ab3f5d',
    messagingSenderId: '974146683624',
    projectId: 'raices-vivas-7ad92',
    authDomain: 'raices-vivas-7ad92.firebaseapp.com',
    storageBucket: 'raices-vivas-7ad92.firebasestorage.app',
    measurementId: 'G-KKY451RF0G',
  );
}
